---
title: "Carnet de Laboratoire : Vitesse de réaction chimique"
author: '...'
date: "..."
output: 
  html_document: 
    toc: yes
    number_sections: yes
    code_folding: hide
---

<!--% Complétez l'entête YAML ci-dessus.-->

```{r setup}
SciViews::R
```

# Introduction 

<!--% Proposez une introduction de 5 phrases sur l'équation de michaelis-Menten.-->

<!--% Ajoutez l'équation de Michaelis-Menten -->

$$ ... $$

# Analyses

<!-- Importez vos données et ajoutez des labels et unités si cela est nécessaire. -->

```{r importation}

```

## Description des données

<!--% Réalisez un graphique qui décrit la vitesse de réaction en fonction de la concentration. Interprétez votre graphique en texte Markdown juste en dessous en maximum 3 phrases. -->

```{r plot1}

```

## Modélisation 

<!--% Modélisation la réaction chimique. -->

```{r model}

```

<!--% Proposez un résumé de votre modèle. Interprétez ce résumé en texte Markdown juste en dessous en maximum 3 phrases. -->

```{r summary}

```

<!--% Réalisez un graphique qui décrit la vitesse de réaction en fonction de la concentration avec la courbe associée à votre modèle. Interprétez votre graphique en texte Markdown juste en dessous en maximum 3 phrases. -->

```{r plot2}

```

<!--% Ajoutez l'équation paramétrée de votre modèle -->

$$ ... $$

# Discussion et conclusions

<!-- Proposez une conclusion de 3 phrases maximum.--> 


